// <auto-generated />
using System;
using DzTaskManager.DBclasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DzTaskManager.Migrations
{
    [DbContext(typeof(TaskDBContext))]
    [Migration("20250530203215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("DzTaskManager.DBclasses.Task", b =>
                {
                    b.Property<Guid>("Task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Task_id");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
